name: hpcpython
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - numexpr
  - matplotlib
  - cython
  - cffi
  - mpi4py
  - ipykernel
  - scipy
  - black
  - mypy
  - bandit
  - pylint
  - flake8
  - pydocstyle
  - line_profiler
  - memory_profiler
  - psutil
